services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: logiclingo
      POSTGRES_USER: root
      POSTGRES_PASSWORD: logiclingo_root
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command: sh -c "
      python manage.py migrate &&
      gunicorn logiclingo.wsgi:application --bind 0.0.0.0:80 --workers 3
      "
    volumes:
      - .:/app
    ports:
      - "80:80"
    environment: #modify these environment variables to fit your needs
      DB_NAME: logiclingo
      DB_USER: root
      DB_PASSWORD: logiclingo_root
      DB_HOST: db
      DB_PORT: 5432
      SECRET_KEY: EFWFEWfehEvb&361^1#@93110 
    depends_on:
      - db

volumes:
  postgres_data:
