services:
  db:
    image: postgres:14
    environment: #make sure these database credentials match what you defined below
      POSTGRES_DB: logiclingo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: logiclingo_postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command: sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn logiclingo.wsgi:application --bind 0.0.0.0:80 --workers 3"
    volumes:
      - .:/app
    ports:
      - "80:80"
    environment: #modify these environment variables to fit your needs
      DB_NAME: logiclingo
      DB_USER: postgres
      DB_PASSWORD: logiclingo_postgres
      DB_HOST: localhost
      DB_PORT: 5432
      SECRET_KEY: EFWFEWfehEvb&361^1#@93110 
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
