# Generated by Django 5.1.6 on 2025-03-13 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='main.classroom'),
        ),
        migrations.AddField(
            model_name='topic',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
