# Generated by Django 5.1.6 on 2025-02-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroomID', models.AutoField(primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('open', models.BooleanField(default=True)),
                ('classroomCode', models.CharField(blank=True, max_length=5, unique=True)),
            ],
        ),
    ]
