# Generated by Django 5.1.5 on 2025-02-28 00:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("userID", models.AutoField(primary_key=True, serialize=False)),
                ("firstName", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("username", models.CharField(max_length=25, unique=True)),
                (
                    "password",
                    models.CharField(
                        max_length=20,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                ("feedback", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("department", models.CharField(max_length=200)),
                ("employed", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("main.user",),
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("numExercisesCompleted", models.IntegerField(default=0)),
                ("numHoursSpent", models.IntegerField(default=0)),
                ("daysStreak", models.IntegerField(default=0)),
                ("streakToday", models.BooleanField(default=False)),
                ("enrolled", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("main.user",),
        ),
        migrations.CreateModel(
            name="Classroom",
            fields=[
                ("classroomID", models.AutoField(primary_key=True, serialize=False)),
                ("className", models.CharField(max_length=100)),
                ("startDate", models.DateField()),
                ("endDate", models.DateField()),
                ("active", models.BooleanField(default=True)),
                ("open", models.BooleanField(default=True)),
                ("instructorName", models.CharField(default="", max_length=200)),
                (
                    "classroomCode",
                    models.CharField(blank=True, max_length=5, unique=True),
                ),
                (
                    "instructors",
                    models.ManyToManyField(
                        related_name="classrooms", to="main.instructor"
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True, related_name="classrooms", to="main.student"
                    ),
                ),
            ],
        ),
    ]
