# Generated by Django 5.1.5 on 2025-02-28 00:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
    ]
