# Generated by Django 5.1.5 on 2025-02-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('feedback', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('employed', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('feedback', models.CharField(max_length=200)),
                ('numExercisesCompleted', models.IntegerField()),
                ('numHoursSpent', models.IntegerField()),
                ('daysStreak', models.IntegerField()),
                ('streakToday', models.BooleanField(default=True)),
                ('enrolled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
