# Generated by Django 5.1.5 on 2025-01-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='classroomCode',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
