# Generated by Django 5.1.5 on 2025-05-07 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultipleChoice",
            fields=[
                (
                    "question_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.question",
                    ),
                ),
                ("choiceA", models.CharField(max_length=255)),
                ("choiceB", models.CharField(max_length=255)),
                ("choiceC", models.CharField(max_length=255)),
                ("choiceD", models.CharField(max_length=255)),
            ],
            bases=("main.question",),
        ),
        migrations.CreateModel(
            name="TrueFalse",
            fields=[
                (
                    "question_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.question",
                    ),
                ),
            ],
            bases=("main.question",),
        ),
    ]
