# Generated by Django 5.1.6 on 2025-04-19 00:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_invitedstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_questions', to='main.instructor'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.exercise'),
        ),
    ]
