# Generated by Django 5.1.5 on 2025-02-25 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_instructor_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='password',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='daysStreak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='numExercisesCompleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='numHoursSpent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='streakToday',
            field=models.BooleanField(default=False),
        ),
    ]
