# Generated by Django 5.1.5 on 2025-03-13 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exerciseID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('exerciseName', models.CharField(max_length=200)),
                ('exerciseDescription', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('questionType', models.CharField(choices=[('fill_blank', 'Fill in the Blank'), ('click_drag', 'Click and Drag'), ('matching', 'Matching'), ('ordering', 'Ordering'), ('translating', 'Translating'), ('multiple_choice', 'Multiple Choice')], max_length=100)),
                ('questionPrompt', models.TextField()),
                ('correctAnswer', models.TextField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.exercise')),
            ],
        ),
    ]
