# Generated by Django 5.1.5 on 2025-04-25 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_invitedstudent"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
