# Generated by Django 5.1.5 on 2025-03-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topicID', models.AutoField(primary_key=True, serialize=False)),
                ('topicName', models.TextField()),
                ('topicDescription', models.TextField()),
                ('topicNote', models.TextField()),
            ],
        ),
    ]
