# Generated by Django 5.1.6 on 2025-05-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_question_created_at_question_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
