# Generated by Django 5.1.6 on 2025-02-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_instructor_password_alter_student_daysstreak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='instructorLastName',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='instructor',
            name='classrooms',
            field=models.ManyToManyField(blank=True, to='main.classroom'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='enrolled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='classrooms',
            field=models.ManyToManyField(blank=True, to='main.classroom'),
        ),
    ]
