# Generated by Django 5.1.6 on 2025-02-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_classroom_instructorlastname_instructor_classrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classrooms',
            field=models.ManyToManyField(related_name='students', to='main.classroom'),
        ),
    ]
